# Generated by Django 5.2.17 on 2026-09-28 18:29

import django.db.models.deletion
from django.db import migrations, models


def seed_pointer(apps, schema_editor):
    PublicationPointer = apps.get_model('core', 'PublicationPointer')
    PublicationPointer.objects.get_or_create(name='wdi_publication')


def reverse_seed_pointer(apps, schema_editor):
    PublicationPointer = apps.get_model('core', 'PublicationPointer')
    PublicationPointer.objects.filter(name='wdi_publication').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationPointer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='wdi_publication', max_length=50, unique=True)),
                ('locked_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Monotonically increasing sequence number for this publication.', unique=True)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 of canonical normalized observations and provenance.', max_length=64)),
                ('retrieved_at', models.DateTimeField(help_text='Timestamp when CiteGrid fetched the provider response.')),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this snapshot was committed into the ledger.')),
                ('source_id', models.CharField(default='2', max_length=10)),
                ('source_name', models.CharField(default='World Development Indicators', max_length=100)),
                ('scope_countries', models.JSONField(default=list, help_text="Fixed list of economies covered (['NGA', 'GHA', 'KEN']).")),
                ('scope_indicators', models.JSONField(default=list, help_text='Fixed list of indicators covered.')),
                ('scope_start_year', models.IntegerField(default=2000)),
                ('scope_end_year', models.IntegerField()),
                ('is_latest', models.BooleanField(db_index=True, default=False, help_text='True if this is the currently active latest published snapshot.')),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_latest', True)), fields=('is_latest',), name='unique_latest_published_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='STARTED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('request_urls', models.JSONField(default=list)),
                ('page_metadata', models.JSONField(default=list)),
                ('pages_fetched', models.IntegerField(default=0)),
                ('records_count', models.IntegerField(default=0)),
                ('error_category', models.CharField(blank=True, max_length=50, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('attempted_url', models.CharField(blank=True, max_length=500, null=True)),
                ('normalized_content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('is_simulation', models.BooleanField(default=False, help_text='True if imported from a simulated fixture or test scenario.')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to='core.snapshot')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(default='2', max_length=10)),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('indicator_code', models.CharField(max_length=50)),
                ('indicator_name', models.CharField(max_length=255)),
                ('observation_year', models.IntegerField()),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=8, help_text='Lossless normalized numeric observation, or null if missing.', max_digits=16, null=True)),
                ('raw_value_str', models.CharField(blank=True, help_text='Exact string representation returned by provider before parsing.', max_length=50, null=True)),
                ('footnote', models.TextField(blank=True, default='')),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('obs_status', models.CharField(blank=True, default='', max_length=50)),
                ('indicator_definition', models.TextField()),
                ('provider_label', models.CharField(default='World Bank', max_length=100)),
                ('source_url', models.URLField(max_length=500)),
                ('license', models.CharField(default='CC BY 4.0', max_length=100)),
                ('underlying_source', models.CharField(default='SDG 7.1.1 electrification dataset', max_length=255)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.snapshot')),
            ],
            options={
                'ordering': ['country_code', 'indicator_code', 'observation_year'],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'source_id', 'country_code', 'indicator_code', 'observation_year'), name='unique_snapshot_observation')],
            },
        ),
        migrations.RunPython(seed_pointer, reverse_seed_pointer),
    ]
