# Generated by Django 5.2.17 on 2026-09-28 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(default='2', max_length=10)),
                ('country_code', models.CharField(max_length=3)),
                ('country_name', models.CharField(max_length=100)),
                ('indicator_code', models.CharField(max_length=50)),
                ('indicator_name', models.CharField(max_length=255)),
                ('observation_year', models.IntegerField()),
                ('transition_type', models.CharField(choices=[('NEW_VALUE', 'New value'), ('CHANGED', 'Changed'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('old_value', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('old_raw_value_str', models.CharField(blank=True, max_length=50, null=True)),
                ('new_raw_value_str', models.CharField(blank=True, max_length=50, null=True)),
                ('old_footnote', models.TextField(blank=True, default='')),
                ('new_footnote', models.TextField(blank=True, default='')),
                ('old_unit', models.CharField(blank=True, default='', max_length=50)),
                ('new_unit', models.CharField(blank=True, default='', max_length=50)),
                ('old_indicator_definition', models.TextField(blank=True, default='')),
                ('new_indicator_definition', models.TextField(blank=True, default='')),
                ('old_source_url', models.URLField(blank=True, default='', max_length=500)),
                ('new_source_url', models.URLField(blank=True, default='', max_length=500)),
                ('old_provider_label', models.CharField(blank=True, default='', max_length=100)),
                ('new_provider_label', models.CharField(blank=True, default='', max_length=100)),
                ('old_license', models.CharField(blank=True, default='', max_length=100)),
                ('new_license', models.CharField(blank=True, default='', max_length=100)),
                ('old_underlying_source', models.CharField(blank=True, default='', max_length=255)),
                ('new_underlying_source', models.CharField(blank=True, default='', max_length=255)),
                ('previous_retrieved_at', models.DateTimeField()),
                ('current_retrieved_at', models.DateTimeField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('current_snapshot', models.ForeignKey(help_text='Later snapshot in the adjacent comparison.', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_revisions', to='core.snapshot')),
                ('new_snapshot_value', models.ForeignKey(blank=True, help_text='Reference to the later snapshot value record, if present.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions_as_new', to='core.snapshotvalue')),
                ('old_snapshot_value', models.ForeignKey(blank=True, help_text='Reference to the earlier snapshot value record, if present.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions_as_old', to='core.snapshotvalue')),
                ('previous_snapshot', models.ForeignKey(help_text='Earlier snapshot in the adjacent comparison.', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_revisions', to='core.snapshot')),
            ],
            options={
                'ordering': ['-current_snapshot__version', 'country_code', 'indicator_code', '-observation_year'],
                'constraints': [models.UniqueConstraint(fields=('previous_snapshot', 'current_snapshot', 'source_id', 'country_code', 'indicator_code', 'observation_year'), name='unique_snapshot_revision_key')],
            },
        ),
    ]
