# Generated by Django 5.2.17 on 2026-09-28 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('indicator_code', models.CharField(help_text='Indicator code compared across countries.', max_length=50)),
                ('countries', models.JSONField(default=list, help_text='Canonically sorted, non-empty list of ISO3 economy codes.')),
                ('start_year', models.IntegerField(help_text='Inclusive start observation year.')),
                ('end_year', models.IntegerField(help_text='Inclusive end observation year.')),
                ('is_public_example', models.BooleanField(db_index=True, default=False, help_text='Designates the single public read-only example comparison.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Optional analyst owner if authentication is enabled.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_comparisons', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(help_text='The immutable snapshot to which this comparison is pinned.', on_delete=django.db.models.deletion.PROTECT, related_name='saved_comparisons', to='core.snapshot')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_public_example', True)), fields=('is_public_example',), name='unique_single_public_example')],
            },
        ),
    ]
